---
- name: Install nginx packages
  dnf:
    name:
      - nginx
    state: present

- name: Remove old configuration files
  file:
    state: absent
    path: "{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: "{{ nginx_conf_path }}/conf.d", file: "default.conf"}

- name: Creation of nginx configuration file
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ item.path }}/{{ item.file }}"
    mode: '0644'
    owner: root
    group: root
  with_items:
    - { path: "{{ nginx_conf_path }}", file: "nginx.conf"}


- name: Verify Nginx configuration before restarting
  command: nginx -t
  changed_when: false


- name: Restart service nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: not ansible_check_mode